credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$GYkqqIhhHZh4CieD9Wazf.jKny.QDWBGBCw9k1BIw6Z0B2yhgOW5e
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - admin@example.com 